#pragma once

#ifndef CONFIG_INK_RUN_EINK_BRINGUP_ON_BOOT
#define CONFIG_INK_RUN_EINK_BRINGUP_ON_BOOT 0
#endif

#ifndef CONFIG_INK_PANEL_CLEAR_BEFORE_DRAW
#define CONFIG_INK_PANEL_CLEAR_BEFORE_DRAW 0
#endif

#ifndef CONFIG_AUDIO_RECORD_BUTTON_GPIO
#define CONFIG_AUDIO_RECORD_BUTTON_GPIO 9
#endif

#ifndef CONFIG_AUDIO_RECORD_DURATION_MS
#define CONFIG_AUDIO_RECORD_DURATION_MS 10000
#endif

#ifndef CONFIG_AUDIO_RECORD_SAMPLE_RATE
#define CONFIG_AUDIO_RECORD_SAMPLE_RATE 16000
#endif

#ifndef CONFIG_AUDIO_PORTAL_AP_SSID
#define CONFIG_AUDIO_PORTAL_AP_SSID "INK-ESP-AUDIO"
#endif

#ifndef CONFIG_AUDIO_PORTAL_WIFI_START_DELAY_MS
#define CONFIG_AUDIO_PORTAL_WIFI_START_DELAY_MS 2000
#endif

#ifndef CONFIG_AUDIO_PORTAL_WIFI_MAX_TX_POWER_QDBM
#define CONFIG_AUDIO_PORTAL_WIFI_MAX_TX_POWER_QDBM 84
#endif

#ifndef CONFIG_AUDIO_PORTAL_BUTTON_LONG_PRESS_MS
#define CONFIG_AUDIO_PORTAL_BUTTON_LONG_PRESS_MS 3000
#endif

#ifndef CONFIG_AUDIO_PORTAL_STA_AUTOCONNECT_DELAY_MS
#define CONFIG_AUDIO_PORTAL_STA_AUTOCONNECT_DELAY_MS 15000
#endif

#ifndef CONFIG_AUDIO_PORTAL_DIAGNOSTIC_WIFI_ONLY
#define CONFIG_AUDIO_PORTAL_DIAGNOSTIC_WIFI_ONLY 0
#endif
