#pragma once

#ifndef CONFIG_INK_RUN_EINK_BRINGUP_ON_BOOT
#define CONFIG_INK_RUN_EINK_BRINGUP_ON_BOOT 0
#endif

#ifndef CONFIG_INK_PANEL_CLEAR_BEFORE_DRAW
#define CONFIG_INK_PANEL_CLEAR_BEFORE_DRAW 0
#endif

#ifndef CONFIG_AUDIO_RECORD_BUTTON_GPIO
#define CONFIG_AUDIO_RECORD_BUTTON_GPIO 9
#endif

#ifndef CONFIG_AUDIO_RECORD_DURATION_MS
#define CONFIG_AUDIO_RECORD_DURATION_MS 3000
#endif

#ifndef CONFIG_AUDIO_RECORD_SAMPLE_RATE
#define CONFIG_AUDIO_RECORD_SAMPLE_RATE 24000
#endif

#ifndef CONFIG_AUDIO_ES8311_INPUT_GAIN_DB
#define CONFIG_AUDIO_ES8311_INPUT_GAIN_DB 30
#endif

#ifndef CONFIG_AUDIO_PLAYBACK_VOLUME
#define CONFIG_AUDIO_PLAYBACK_VOLUME 100
#endif

#ifndef CONFIG_AUDIO_CAPTURE_PROCESSING
#define CONFIG_AUDIO_CAPTURE_PROCESSING 0
#endif

#ifndef CONFIG_AUDIO_CAPTURE_NOISE_GATE
#define CONFIG_AUDIO_CAPTURE_NOISE_GATE 0
#endif

#ifndef CONFIG_AUDIO_CAPTURE_AGC
#define CONFIG_AUDIO_CAPTURE_AGC 0
#endif

#ifndef CONFIG_AUDIO_CAPTURE_AGC_TARGET_AVG
#define CONFIG_AUDIO_CAPTURE_AGC_TARGET_AVG 1100
#endif

#ifndef CONFIG_AUDIO_CAPTURE_AGC_MAX_GAIN_X100
#define CONFIG_AUDIO_CAPTURE_AGC_MAX_GAIN_X100 250
#endif

#ifndef CONFIG_AUDIO_CAPTURE_SOFT_LIMITER
#define CONFIG_AUDIO_CAPTURE_SOFT_LIMITER 0
#endif

#ifndef CONFIG_AUDIO_LOOPBACK_DC_BLOCK
#define CONFIG_AUDIO_LOOPBACK_DC_BLOCK 1
#endif

#ifndef CONFIG_AUDIO_BOOT_TEST_TONE
#define CONFIG_AUDIO_BOOT_TEST_TONE 1
#endif

#ifndef CONFIG_AUDIO_BOOT_TEST_TONE_MS
#define CONFIG_AUDIO_BOOT_TEST_TONE_MS 700
#endif

#ifndef CONFIG_AUDIO_PORTAL_AP_SSID
#define CONFIG_AUDIO_PORTAL_AP_SSID "INK-ESP-AUDIO"
#endif

#ifndef CONFIG_AUDIO_PORTAL_WIFI_START_DELAY_MS
#define CONFIG_AUDIO_PORTAL_WIFI_START_DELAY_MS 2000
#endif

#ifndef CONFIG_AUDIO_PORTAL_WIFI_MAX_TX_POWER_QDBM
#define CONFIG_AUDIO_PORTAL_WIFI_MAX_TX_POWER_QDBM 84
#endif

#ifndef CONFIG_AUDIO_PORTAL_BUTTON_LONG_PRESS_MS
#define CONFIG_AUDIO_PORTAL_BUTTON_LONG_PRESS_MS 3000
#endif

#ifndef CONFIG_AUDIO_PORTAL_STA_AUTOCONNECT_DELAY_MS
#define CONFIG_AUDIO_PORTAL_STA_AUTOCONNECT_DELAY_MS 15000
#endif

#ifndef CONFIG_AUDIO_PORTAL_DIAGNOSTIC_WIFI_ONLY
#define CONFIG_AUDIO_PORTAL_DIAGNOSTIC_WIFI_ONLY 0
#endif
