#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_1
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_3
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_2
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_0

#define AUDIO_CODEC_PA_PIN      GPIO_NUM_NC
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_21
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_20
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR

#define BOOT_BUTTON_GPIO GPIO_NUM_9

#define DISPLAY_SPI_HOST SPI2_HOST
#define DISPLAY_SPI_SCK_PIN  GPIO_NUM_7
#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_6
#define DISPLAY_SPI_CS_PIN   GPIO_NUM_8
#define DISPLAY_DC_PIN       GPIO_NUM_10
#define DISPLAY_RST_PIN      GPIO_NUM_NC
#define DISPLAY_BUSY_PIN     GPIO_NUM_NC

#define DISPLAY_WIDTH    104
#define DISPLAY_HEIGHT   212
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY  false

#define BOARD_IOX_ADDR                0x20
#define BOARD_IOX_BIT_EINK_RES        1
#define BOARD_IOX_BIT_EINK_CTRL_4150B 2

#define DISPLAY_SPI_CLOCK_HZ (4 * 1000 * 1000)
#define DISPLAY_RESET_HOLD_MS    20
#define DISPLAY_RESET_RELEASE_MS 20
#define DISPLAY_POWER_SETTLE_MS  30

#endif // _BOARD_CONFIG_H_
